### ISSUE TITLE
Move FAST subject conversion changes from dev to production

### ISSUE THREAD

**Issue by amareshjoshi** [MESH-Research/humcore#180]
Basic steps

- push source code changes to production branch
- convert subject and keyword/tag lists for each deposit (17k)
- final testing

**Comment by amareshjoshi** [comment]
- Bring humcore plugin up to date. Push changes to main branch
- Run scripts on development system systems (msudev and hcdev)
    - notify authors script - pulls data on deposit changes to create author notification emails
    - save metadata - saves metadata on ALL deposits to a text file in case of disaster recovery
    - update metadata (subjects and keywords/tags)
- Run scripts on production system system
- Update external systems
    - SOLR
    - Fedora
    - MODS
    - DataCite
- Test

**Comment by ericknappe** [comment]
I'd like to see this run in DEV first. I'd prefer seeing it run against the latest deposits but, we can run against what's there which is from January I think.

Steps needed for running against the latest deposits
Update msucommons-dev with latest data from HC ~6 hours.
Update MSU Fedora with latest deposits ~4 hours.

**Comment by ericknappe** [comment]
The MSU Fedora application has a devel instance and a prod instance, both msucommons-dev (MSUDEV) and hcommons-dev (HCDEV) are connected to the MSU devel Fedora instance. Deposits in Solr will not display correctly on the Commons if the Commons DB is not current with the associated Fedora instance. This is not a problem with Commons testing and development outside of CORE. The MSU devel Fedora instance was last loaded for the cutover from CUL Fedora to MSU Fedora. There have been 800-1000 deposits in production since that time. The Wordpress networks contain records that drive that FAST migration process, the Solr reindex process and the MODS and Datacite migration processes. MSUDEV and HCDEV have not been refreshed recently, but are more recent than the MSU devel Fedora snapshot. This condition resulted in about 400 errors when updating Solr and MODS after the first full run of the FAST migration script. Since the MSUDEV snapshot and the HCDEV snapshot are from different points in time, running the FAST migration script on HCDEV right now will not offer much benefit and may introduce confusion due to the deposits available at different points in time.

In order to get the most complete test I suggest the following:

* Update MSUDEV to a recent snapshot of Hcommons
* Run the process that inserts and indexes deposits into the MSU Devel Fedora instance
* Run scripts on a development system MSUDEV
        notify authors script - pulls data on deposit changes to create author notification emails.
        save metadata - saves metadata on ALL deposits to a text file in case of disaster recovery
        update metadata (subjects and keywords/tags)

Refreshing Fedora and WP with current data will increase test coverage and minimize the potential for unanticipated issues from a large number (800-1000) of deposits never being migrated in test. Running the FAST migration scripts on HCDEV in addition to MSUDEV has limited value for testing if HCDEV is not in sync with the Hcommons snapshot used for the Solr and MODS updates. Therefore, I would like to sync HCDEV with the same snapshot used on MSUDEV prior to running the FAST migration in HCDEV. Solr and MODS updates will not be necessary. There may be an additional 50 deposits in prod between the snapshot and the prod cutover, that should not present much of a problem.

**Comment by ericknappe** [comment]
The email from Google Scholar regarding the 404 return code from CORE deposits in mla.hcomons.org identifies another post FAST migration need. After the FAST migration, we should contact Google Scholar and request reindexing of all networks.

**Comment by ericknappe** [comment]
I have not begun the sync of MSUDEV yet, I'm correcting some deposit problems in prod so that that copy will be as clean as possible.

Amaresh has given me the okay to sync MSUDEV (data and user uploads). @mikethicke, I would like to resync HCDEV (data and user uploads) at the same time. I can do this over the long weekend to allow testing next week.

**Comment by mikethicke** [comment]
Sounds good, thanks @ericknappe

**Comment by amareshjoshi** [comment]
1. Testing was done on msudev (twice) and hcdev. 
2. Merge feature-FAST branch with main
3. Merge main branch with production branch
4. Merge on production server

**Comment by amareshjoshi** [comment]
Deposit metadata has been converted. We are waiting for indexing programs to run (solr, MODS, Datacite). There are some delays due to hardware failure on the MSU Library stack

**Comment by amareshjoshi** [comment]
All the metadata has been converted.
